name: Release on tag

on:
  workflow_dispatch:
    inputs:
      pypi:
        description: Release to PyPI
        type: boolean
        default: true
      testpypi:
        description: Release to Test PyPI
        type: boolean
        default: false

jobs:
  test:
    uses: ./.github/workflows/test-lib.yml
  build:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install .[dist]
        working-directory: lib/
      - name: Build
        run: |
          python -m build
        working-directory: lib/
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: packages
          path: |
            lib/dist/string_fixer*.whl
            lib/dist/string_fixer*.tar.gz
  release:
    needs: [build]
    runs-on: ubuntu-latest
    environment: release-env
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: packages
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Publish to Test PyPI
        if: ${{ inputs.testpypi == true }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          packages-dir: ./
          repository-url: https://test.pypi.org/legacy/
      - name: Publish to PyPI
        if: ${{ inputs.pypi == true || github.event_name == 'push' }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages-dir: ./
